# Generated by Django 6.0.2 on 2026-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('requester', 'Requester'), ('vendor', 'Vendor')], default='requester', max_length=20),
        ),
    ]
