# Generated by Django 3.0.6 on 2020-05-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_pr_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='total',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='pr',
            name='category',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Facility Management', 'Facility Management'), ('General Goods and Sevices', 'General Goods and Sevices'), ('Inormation Technology', 'Information Technlogy'), ('Office Supplies', 'Office Supplies')], default='Choose Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='pr',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Approval', 'Approval'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
    ]
