# Generated by Django 3.0.6 on 2020-05-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0004_auto_20200524_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
