# Generated by Django 6.0.2 on 2026-02-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0006_alter_pr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='payment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pr',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='pr',
            name='vendor_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pr',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
