# Generated by Django 6.0.2 on 2026-02-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0009_vendor_approved_by_vendor_approved_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='estimated_price',
            field=models.FloatField(blank=True, help_text="Vendor's estimated price", null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='item_type',
            field=models.CharField(blank=True, help_text='Type of item/service needed', max_length=200),
        ),
        migrations.AddField(
            model_name='pr',
            name='items_description',
            field=models.TextField(blank=True, help_text='Detailed description of items needed'),
        ),
        migrations.AddField(
            model_name='pr',
            name='price_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pr',
            name='price_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pr',
            name='price_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='quantity',
            field=models.CharField(blank=True, help_text='Quantity needed (e.g., 10 units, 5 boxes)', max_length=100),
        ),
        migrations.AddField(
            model_name='pr',
            name='quotation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='quotation_notes',
            field=models.TextField(blank=True, help_text="Vendor's quotation notes and breakdown"),
        ),
        migrations.AddField(
            model_name='pr',
            name='quotation_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pr',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specifications or requirements'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional notes and comments'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='total',
            field=models.FloatField(default=0.0, help_text='Final approved price', max_length=100),
        ),
    ]
