# Generated by Django 6.0.2 on 2026-02-16 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0010_pr_estimated_price_pr_item_type_pr_items_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='category',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Facility Management', 'Facility Management'), ('General Goods and Services', 'General Goods and Services'), ('Information Technology', 'Information Technology'), ('Office Supplies', 'Office Supplies')], default='Choose Category', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.FloatField(help_text="Vendor's quoted price")),
                ('quotation_notes', models.TextField(blank=True, help_text='Price breakdown and details')),
                ('quotation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_selected', models.BooleanField(default=False, help_text='Selected by buyer')),
                ('selected_date', models.DateTimeField(blank=True, null=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='prs.pr')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_selected', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='prs.vendor')),
            ],
            options={
                'ordering': ['estimated_price'],
                'unique_together': {('pr', 'vendor')},
            },
        ),
    ]
