# Generated by Django 6.0.2 on 2026-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0011_alter_pr_category_vendorquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Delivery address provided by requester'),
        ),
        migrations.AddField(
            model_name='pr',
            name='payment_method_used',
            field=models.CharField(blank=True, default='', help_text='Payment method used by requester', max_length=100),
        ),
        migrations.AddField(
            model_name='pr',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', help_text='Online payment transaction ID', max_length=200),
        ),
        migrations.AddField(
            model_name='pr',
            name='requester_approved_quotation',
            field=models.BooleanField(default=False, help_text='Requester approved the quotation and paid'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='categories',
            field=models.CharField(blank=True, help_text='Select categories you serve (comma-separated)', max_length=500),
        ),
    ]
