# Generated by Django 6.0.2 on 2026-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0012_add_payment_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_holder',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code for bank transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for payments (e.g. vendor@upi)', max_length=100),
        ),
    ]
